### PR TITLE
Features: AM-397 & AM-398

### PR DESCRIPTION
**Pull request by johanfol**
* AM-397 & AM-398;
* Added UML diagrams explaining gRPC and OpenFaaS issue.
Fixes:
* Fix CRSP to asynchronously send requests to Rule Engines;

### CODE REVIEW

**Review by aaronreynoza — APPROVED** [review]

**Review by joeygoksu — APPROVED** [review]

**Comment by johanfol** [comment]
@elnyry-sam-k  created an issue on the cla-assitant - I'm unable to sign the CLA for some reason. Details here:
https://github.com/cla-assistant/cla-assistant/issues/701

I've signed it before, but working from a new PC it wants me to sign again. 

Is it fine if I merge this PR even though it thinks I didn't sign?

**Comment by elnyry-sam-k** [comment]
@johanfol - any chance your other machine is using a different GitHub ID (or isn't configured to use one)?

**Comment by elnyry-sam-k** [comment]
> @elnyry-sam-k created an issue on the cla-assitant - I'm unable to sign the CLA for some reason. Details here:
> [cla-assistant/cla-assistant#701](https://github.com/cla-assistant/cla-assistant/issues/701)
> 
> I've signed it before, but working from a new PC it wants me to sign again.
> 
> Is it fine if I merge this PR even though it thinks I didn't sign?

Its fine with merging for now - if its blocking your work

**Comment by johanfol** [comment]
> @johanfol - any chance your other machine is using a different GitHub ID (or isn't configured to use one)?

Same GitHub ID - if you click on my UserID you should see all my previous PR's to the same repository, with this GitHub ID.

**Pull request merged**
